axis_linear: 
  x: 1 # Left thumb stick vertical
  y: 0 # Right thumb stick horizontal
scale_linear: 
  x: 0.7
  y: 0.7
scale_linear_turbo: 
  x: 1.0
  y: 1.0

axis_angular: 3  # Left thumb stick horizontal
scale_angular: 0.7
scale_linear_turbo: 1.0


enable_button: 4  # Left trigger button
enable_turbo_button: 5  # Right trigger button
